# Generated by Django 5.0.3 on 2024-04-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
        migrations.AddField(
            model_name='contact',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
